name: Embedded code in README

on: [push]

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}

      - uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "synchronizing README"
          silent: false
